version: 2.1

jobs:
  build:    
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: nuget restore
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  win: circleci/windows@1.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
